apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsc-realtime-ingestion
  namespace: ingestion
  labels:
    chain: bsc
    pipeline: bsc_mainnet_ingestion
  annotations:
    reloader.stakater.com/auto: "true"
    
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      chain: bsc
      pipeline: bsc_mainnet_ingestion
  template:
    metadata:
      labels:
        chain: bsc
        pipeline: bsc_mainnet_ingestion
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
      containers:
        - name: rpcstream-dev
          image: rpcstream:dev
          imagePullPolicy: IfNotPresent

          # -----------------------------
          # Ingest runtime variables
          # -----------------------------
          env:
            - name: PIPELINE_CONFIG
              value: /config/pipeline.yaml

            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          volumeMounts:
            - name: config-volume
              mountPath: /config

          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "256Mi"

      volumes:
        - name: config-volume
          configMap:
            name: bsc-realtime-ingestion