pipeline:
  type: "block"
  mode: "realtime"

adapter:
  type: "evm"
  chain: "bsc"
  network: "mainnet"

schema:
  entities: ["block", "transaction"]

rpc:
  endpoint: "http://localhost:30040/main/evm/56"
  timeout_sec: 10
  inflight:
    initial: 5
    max: 10
    target: 1000

engine:
  concurrency: 20 # concurrency for parallel processing and sink

kafka:
  bootstrap_servers: "localhost:30092"

  security:
    # protocol: "SASL_SSL"
    mechanism: "PLAIN"

  auth:
    username_env: "KAFKA_USERNAME"
    password_env: "KAFKA_PASSWORD"

  producer:
    linger_ms: 10
    batch_size: 65536

  streaming:
    batch_size: 100          # micro-batch size
    flush_interval_ms: 20    # max wait time
    queue_maxsize: 1000      # backpressure control


log:
  level: "info"