kubectl create secret generic kafka-credentials -n ingestion\
  --from-literal=KAFKA_USERNAME=<your-kafka-username> \
  --from-literal=KAFKA_PASSWORD=<your-kafka-password> \
  --from-literal=KAFKA_BOOTSTRAP_SERVERS=<your-bootstrap-server>