apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsc-block-transaction-ingestion-otel
  namespace: ingestion
  labels:
    app: block-transaction-ingestion-otel
    chain: bsc
  annotations:
    reloader.stakater.com/auto: "true"
    
spec:
  replicas: 1
  strategy:
    type: Recreate
    #  kill old takes time and ingestion continus while the pod is in terminating status, ingestion paused for 1 sec only
  selector:
    matchLabels:
      app: block-transaction-ingestion-otel
      chain: bsc
  template:
    metadata:
      labels:
        app: block-transaction-ingestion-otel
        chain: bsc
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 1 # EOS is maintained by state topic
      containers:
        - name: ingestion-pipeline-otel
          image: ghcr.io/chainlake/rpcstream:v0.1.5
          imagePullPolicy: IfNotPresent
          command: ["python", "block_pipeline_realtime.py"]

          # -----------------------------
          # Ingest runtime variables
          # -----------------------------
          env:
                         
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          # -----------------------------
          # Metrics endpoint
          # -----------------------------

          # -----------------------------
          # (Optional but recommended)
          # Resource limits
          # -----------------------------
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "256Mi"